### ISSUE TITLE
Pending Projects Not Displayed

### ISSUE THREAD

**Issue by JamesHoustonDavis** [GK-12/rpi_csdt_community#31] opened 2015-01-15 21:37 UTC
Projects Pending Approval is Empty... they do still exist in the admin projects folder though and will appear if approved.

**Comment by chuck211991** [comment] 2015-04-22 03:19
This is intended behavior; once submitted, we don't want students modifying projects until teachers can look at it... But maybe we need to change that? Closing for now

**Closed by chuck211991** 2015-04-22 03:19 UTC
Labels: enhancement, wontfix
