### ISSUE TITLE
Saving Errors In CSnap

### ISSUE THREAD

**Issue by JamesHoustonDavis** [GK-12/rpi_csdt_community#30] opened 2015-01-15 21:17 UTC
If I create a new project, save it to the cloud, and then (without closing) save again -- because I might be actively working on it. I get the error:
![image](https://cloud.githubusercontent.com/assets/8440451/5766750/e9fb81f8-9cd1-11e4-9dcd-e1844fb8c721.png)

**Comment by chuck211991** [comment] 2015-04-22 03:20
Can't reproduce, I believe this was fixed with commit https://github.com/GK-12/rpi_csdt_community/commit/11ef9ec88826e5fb201e59aa61c2426e20569f19

**Closed by chuck211991** 2015-04-22 03:20 UTC
Labels: bug
